#!/bin/bash
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "*** hooks/post_build"

VERSION=$(git describe --tags --always)
COMMIT=$(git rev-parse HEAD)
URL=$(git config --get remote.origin.url)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
for V in {VERSION,COMMIT,URL,BRANCH,DATE,SOURCE_BRANCH,SOURCE_COMMIT,COMMIT_MSG,DOCKER_REPO,DOCKERFILE_PATH,DOCKER_TAG,IMAGE_NAME}; do
echo $(eval "echo $V: \$${V}")
done
# workaround for two steps build
if [[ ${DOCKERFILE_PATH} == 'Dockerfile.release' ]]; then
for I in {full-debug,generator,generator-debug}; do # we skip build for 'full' as it symlinked to DOCKERFILE_REPO already
docker build \
  --build-arg VERSION="${VERSION}" \
  --build-arg COMMIT="${COMMIT}" \
  --build-arg URL="${URL}" \
  --build-arg BRANCH="${BRANCH}" \
  --build-arg DATE="${DATE}" \
  --build-arg SOURCE_BRANCH="${SOURCE_BRANCH}" \
-t "${DOCKER_REPO}:${SOURCE_BRANCH}-${I}" -f "${DOCKERFILE_PATH}" .
done
else
echo "no custom post_build for base image"
fi