#!/bin/bash
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "*** hooks/post_push"

for V in {SOURCE_BRANCH,DOCKER_REPO}; do
echo $(eval "echo $V: \$${V}")
done
if [[ ${DOCKERFILE_PATH} == 'Dockerfile.release' ]]; then
docker tag "${DOCKER_REPO}:${SOURCE_BRANCH}" "${DOCKER_REPO}:${SOURCE_BRANCH}-full" # we need to tag default image with full
docker tag "${DOCKER_REPO}:${SOURCE_BRANCH}" "${DOCKER_REPO}:latest"
docker push "${DOCKER_REPO}:latest"
for I in {full,full-debug,generator,generator-debug}; do
docker push "${DOCKER_REPO}:${SOURCE_BRANCH}-${I}"
done
else
echo "no custom post_push for base image"
fi
